name: finance_tracker
description: Aplikasi pencatatan keuangan pengeluaran dan pemasukan
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  animated_splash_screen: ^1.3.0
  animated_bottom_navigation_bar: ^1.4.0
  shared_preferences: ^2.2.2
  url_launcher: ^6.3.2
  intl: ^0.20.0
  fl_chart: ^0.66.0
  sqflite: ^2.3.0
  path: ^1.8.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/